# FAQtory settings

faq_url: "https://github.com/LooseLab/readfish/blob/refactor/docs/FAQ.md" # Replace this with the URL to your FAQ.md!

questions_path: "./docs/questions" # Where questions should be stored
output_path: "./docs/FAQ.md" # Where FAQ.md should be generated
templates_path: "./.github/faq" # Path to templates
