repos:

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black (python)
        args:
          - '--target-version=py38'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: '(\.patch|\.diff|\.fasta$|\.fastq$|\.sam$|\.rbt$|\.bit$|target/)'
      - id: trailing-whitespace
        exclude: '(target/|\.patch|\.diff|\.fasta$|\.fastq$|\.sam$|\.rbt$|\.bit$)'
      - id: check-ast
      - id: check-toml
