name: issues
on:
  issues:
    types: [opened]
jobs:
  add-comment:
    # https://docs.github.com/en/actions/learn-github-actions/expressions#example-matching-an-array-of-strings
    if: ${{ !contains(fromJSON('["alexomics", "Adoni5", "mattloose"]'), github.actor) }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Install FAQtory
        run: pip install FAQtory
      - name: Run Suggest
        env:
          TITLE: ${{ github.event.issue.title }}
        run: faqtory suggest -c .github/faq.yml "$TITLE" > suggest.md
      - name: Read suggest.md
        id: suggest
        uses: juliangruber/read-file-action@v1
        with:
          path: ./suggest.md
      - name: Suggest FAQ
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.suggest.outputs.content }}
